//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _50DersteMvcProjeKampi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProducts()
        {
            this.tblOrders = new HashSet<tblOrders>();
        }
    
        public short ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductBrand { get; set; }
        public Nullable<short> CategoryId { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<byte> ProductStocks { get; set; }
    
        public virtual tblCategories tblCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrders> tblOrders { get; set; }
    }
}
